### PR TITLE
Upgrade opencv to 4.3.0

### PR DESCRIPTION
**Pull request by czerwinskilukasz1**

### CODE REVIEW

**Comment by drzraf** [comment]
- Is it possible to do this OpenCV update on top of https://github.com/cpvrlab/ImagePlay/pull/111 where I tried to unbundle OpenCv? (I think it's the way to go)
- Which OS was tested for compilation/runtime?

**Comment by czerwinskilukasz1** [comment]
> * Is it possible to do this OpenCV update on top of #111 where I tried to unbundle OpenCv? (I think it's the way to go. Easier to update, easier to review & maintain)

I am not sure whether unbundling OpenCV is the right thing to do right now. This project is not updated on frequently basis, so it's much easier to run into compatibility errors with newer versions of OpenCV. I would leave it bundled for the time being.

> * Which OS was tested for compilation/runtime?

So far I tested on Windows.
I will also test on Linux (Ubuntu) and MacOS when Marcus preliminarily approves this PR.

@hudrima1, what do you think about my idea of upgrading OpenCV to 4.3.0?

**Comment by czerwinskilukasz1** [comment]
@hsm4, would you have a while to let us know what you think?

**Comment by hudrima1** [comment]
Hi Lukasz,
I'm happy that someone takes time for some maintenance and improvements because we don't have time in our group for this project right now. We are busy with the SLProject project. We there use also several libraries among them is also OpenCV. This is a development project where we provide prebuilt versions of some libraries that we download with cmake. 
What about the prebuilt executables for Windows, MacOS and Linux of ImagePlay?
Regards
Marcus

**Comment by czerwinskilukasz1** [comment]
Thank you @hudrima1 for your appreciation and for merging my changes! :) 
I could provide prebuild executables with my change for all 3 OS's. 
Do you have any special requirements on how they should be built?
Where should I upload the executables?

**Comment by hudrima1** [comment]
Hi Lucasz,
we are working almost exclusively on SLProject (https://github.com/cpvrlab/SLProject). It uses also OpenCV among other libraries. Some of them are prebuilt such as OpenCV because their build with Contribs for Win., Macos, Android and iOS is rather painful. We download these prebuilt libraries from an FTP of us. We do this all in cmake. You can see how we do that in the cmake file SLProject/cmake/DownloadPrebuilt/. I would prefer a similar way for ImagePlay before we to prebuilt executables. I just updated Qt and cloned ImagePlay and I can't build because the linked OpenCV libs are still on 3.1. I thought you migrated them to 4.3?
Regards
Marcus

**Pull request merged**
