### PR TITLE
added an "Open recent" menu

### PR DESCRIPTION
**Pull request by costypetrisor**
for issue #60

### CODE REVIEW

**Comment by costypetrisor** [comment]
I hope I got the terminology right ("project" vs "process file"), I inspired myself from your variable name `_currentProcessFileName`.

**Comment by l00mi** [comment]
Nice! Works well on OS X. We will test next week on Windows and Linux and merge if working.

Note: Minor strange behavior, on first load of the application the menu shows the bogus entry "_Recents_".

**Comment by costypetrisor** [comment]
The bogus "Recents" is my mistake, I forgot it in the MainWindow.ui file along with other insignificant changes. I have edited my commit to remove these.

**Comment by l00mi** [comment]
Thanks @costypetrisor for the nice implementation!

**Pull request merged**
