### PR TITLE
Sort Tabs in ImageViewerWindow

### LINKED ISSUE #32: Order tabs in the preview window according to the "depth" of the process in the execution tree
Currently, the tabs in the preview window are still sorted by the in which the processes were created. If the application is used for prototyping, the propability that the processes are not created in a logical order is fairly high. Sorting them by their execution order would minimize confusion.

### PR DESCRIPTION
**Pull request by ladotonia**
pull request to fix #32

### CODE REVIEW

**Comment by schmk2** [comment]
Thanks for your submission. It does not work reliably yet, I'm currently investigating. For easier debugging I'm displaying the `_treeDepth` (which looks correct in the graph but not in the tabs) and deleting/rerouting the graph edges. Somehow `sortTabs` sometimes quits early when there should be some changes in the sorting order (see screenshot).

Please currently don't change anything near `removeEdgeIn`, I am in the process of improving depth ordering when deleting edges.

2015-10-02 11_19_31-imageplay 6 0 0-rc 0

**Comment by ladotonia** [comment]
I think it could have potentially been missing tabs sometimes after the move operation.  I added a commit to the branch that should deal with that.  Also there was a bug where it could break out of the sorting too soon under certain conditions.  Lastly if you re-ordered the edges, it could create gaps in the tree depth due to the max() call in IPProcessGrid, so I switched it always assign depth to the parent's depth+1.

I'm not sure however how your tabs end up with 0: at the front of the name.  It should always rename the tabs when any of them are re-ordered, you might see if taking the if (anyMoved) guard off the last loop in sortTabs to see if that fixes that.

If you can send steps or a file to reproduce the issue, I'd be happy to look into it more.

**Comment by schmk2** [comment]
I changed the tab title to display the treeDepth after sorting for debugging reasons... Sorry for the confusion.

Thanks for the fix. I will try it and merge it with my improvements...

**Comment by schmk2** [comment]
Everything seems to work fine now. I changed the tab title to (treeDepth+1) as I think it makes more sense and allows the user to see in what order the operations were done. Especially when more than one are on the same level (after a plane splitter for example).

**Pull request merged**
